### ISSUE TITLE
Your browser does not support window.crypto with node : expected behavior?

### ISSUE THREAD

**Issue by Subfortytwo** [securesecrets/shade#381]
I am testing the shade JS with this simple example taken from the website:
```
$ cat src/index.js 
import {queryPairConfig, queryFactoryConfig, queryFactoryPairs } from '@shadeprotocol/shadejs'

const output = await queryFactoryPairs({
  contractAddress: 'secret1ja0hcwvy76grqkpgwznxukgd7t8a8anmmx05pp',
  codeHash: '2ad4ed2a4a45fd6de3daca9541ba82c26bb66c76d1c3540de39b509abd26538e',
  startingIndex: 0,
  limit: 25, // determines number of records to return
})
```

```
$ node src/index.js 
file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:15638
            throw new Error("Your browser does not support window.crypto.");
                  ^

Error: Your browser does not support window.crypto.
    at a (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:15638:19)
    at _.GenerateNewSeed (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:16268:32)
    at new _ (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:16260:27)
    at new e.ComputeQuerier (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:30237:132)
    at new e.SecretNetworkClient (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:30937:176)
    at file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:34216:13
    at D._subscribe (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:2129:15)
    at D._trySubscribe (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:1699:19)
    at file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:1695:56
    at errorContext (file:///home/user/shadetest/node_modules/@shadeprotocol/shadejs/dist/shadejs.js:1568:3)

Node.js v18.18.2

```

Is that the expected behavior, because you want us to open the code in a browser?

Thank you.

**Comment by AustinWoetzel** [comment]
can you re-open this issue in the shadejs repo? thanks!
https://github.com/securesecrets/shadejs
